### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Testato** [matthuisman/plugin.video.tester#1]
Hi,
Your tester plugin is a very good idea.

I see that it support 
InputStream Adaptive - Dash with Widevine

It is possible add a test for
InputStream Adaptive - Hls with Widevine ?

I'm one of the developer of LA7 video Kodi plugin, and LA7 switched to Sample-Aes
https://d15umi5iaezxgx.cloudfront.net/OUT/HLS/Live_960x540_.m3u8

Thanks

**Comment by matthuisman** [comment]
Kodi (inputstream adaptive) can't yet play HLS with Widevine.
See here: https://github.com/peak3d/inputstream.adaptive/issues/353

**Comment by Testato** [comment]
Thanks for your answer, i'm very new to widevine video decoding.
I'm one of the developer of La7 plugin, you found it in the official Kodi repo, and it changed the video stream some time ago.
This is the streaming page:
https://www.la7.it/dirette-tv

I played it using EME Logger in Chrome and seems that it first try to use Microsoft PalyReady DRM, and after it try with Widevine. So probabily I can use this.

It is a dash on .mpd, in the source of the page is present also a .m3u8 link, but it use sample-aes and so like you say I cannot use it.

May you check the page and tell me your opinion ?
Thanks in advance
